INSERT INTO [dbo].[P_SUBSCRIPTION_PACKAGE]([NAME],[PRICE],[DURATION]) VALUES('Lifetime, Unlimited Units @ RM 10000',10000,0)
INSERT INTO [dbo].[P_SUBSCRIPTION_PACKAGE]([NAME],[PRICE],[DURATION]) VALUES('10 Years, Unlimited Units @ RM 5000',5000,10)
INSERT INTO [dbo].[P_SUBSCRIPTION_PACKAGE]([NAME],[PRICE],[DURATION]) VALUES('5 Years, Unlimited Units @ RM 3000',3000,5)
