alter table P_PROPERTY_SUBSCRIPTION
add START_DATE	DATETIME,
	END_DATE DATETIME,
	COMMISSION INT
	
alter table P_SUBSCRIPTION_PACKAGE
add PRICE DECIMAL,
	DURATION INT
	
alter table P_SUBSCRIPTION_PACKAGE
drop column PERIOD


CREATE TABLE P_PROPERTY_SUBSCRIPTION_ORDER
(
 ROW_ID						    BIGINT IDENTITY(1,1) NOT NULL
,CREATED						DATETIME
,CREATED_BY						BIGINT
,LAST_UPDATED					DATETIME
,LAST_UPDATED_BY				BIGINT

,ORDER_NUM						NVARCHAR(20)
,ORDER_SUBMITTED_BY				BIGINT
,PROPERTY_ID					BIGINT
,SUBSCRIPTION_PACKAGE_ID		BIGINT
,STATUS							INT

CONSTRAINT P_PROPERTY_SUBSCRIPTION_ORDER_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)

CONSTRAINT P_PROPERTY_SUBSCRIPTION_ORDER_F01 FOREIGN KEY (PROPERTY_ID) REFERENCES P_PROPERTY(ROW_ID),
CONSTRAINT P_PROPERTY_SUBSCRIPTION_ORDER_F02 FOREIGN KEY (SUBSCRIPTION_PACKAGE_ID) REFERENCES P_SUBSCRIPTION_PACKAGE(ROW_ID),
)