alter table P_PROPERTY_SUBSCRIPTION
drop column COMMISSION

alter table P_PROPERTY_SUBSCRIPTION_ORDER
add PRICE decimal,
	AFFILIATE_ID bigint,
	COMMISSION int
	

ALTER TABLE p_accnt ALTER COLUMN NAME nvarchar(255) NULL

CREATE TABLE P_PROPERTY_INVOICE
(
 ROW_ID						    BIGINT IDENTITY(1,1) NOT NULL
,CREATED						DATETIME
,CREATED_BY						BIGINT
,LAST_UPDATED					DATETIME
,LAST_UPDATED_BY				BIGINT

,INVOICE_NUM					NVARCHAR(20)
,INVOICE_DATE					DATETIME
,PROPERTY_ID					BIGINT
,DESCRIPTION					NVARCHAR(MAX)
,AMOUNT							DECIMAL
,STATUS							INT

,PAYMENT_STATUS					INT
,PAYMENT_DATE					DATETIME
,PAYMENT_METHOD					INT
,CHEQUE_NO						NVARCHAR(50)
,TRANSACTION_NO					NVARCHAR(50)
,APPROVAL_CODE					NVARCHAR(50)
,BANK							NVARCHAR(50)

CONSTRAINT P_PROPERTY_INVOICE_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)

CONSTRAINT P_PROPERTY_INVOICE_F01 FOREIGN KEY (PROPERTY_ID) REFERENCES P_PROPERTY(ROW_ID),
)