CREATE TABLE P_SUBSCRIPTION_PACKAGE
(
 ROW_ID						    BIGINT IDENTITY(1,1) NOT NULL
,CREATED						DATETIME
,CREATED_BY						BIGINT
,LAST_UPDATED					DATETIME
,LAST_UPDATED_BY				BIGINT

,NAME							VARCHAR(255)
,PERIOD							INT

CONSTRAINT P_SUBSCRIPTION_PACKAGE_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)
)

CREATE TABLE P_PROPERTY_SUBSCRIPTION
(
 ROW_ID						    BIGINT IDENTITY(1,1) NOT NULL
,CREATED						DATETIME
,CREATED_BY						BIGINT
,LAST_UPDATED					DATETIME
,LAST_UPDATED_BY				BIGINT

,PROPERTY_ID					BIGINT
,SUBSCRIPTION_PACKAGE_ID		BIGINT
,STATUS							INT

CONSTRAINT P_PROPERTY_SUBSCRIPTION_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)

CONSTRAINT P_PROPERTY_SUBSCRIPTION_F01 FOREIGN KEY (PROPERTY_ID) REFERENCES P_PROPERTY(ROW_ID),
CONSTRAINT P_PROPERTY_SUBSCRIPTION_F02 FOREIGN KEY (SUBSCRIPTION_PACKAGE_ID) REFERENCES P_SUBSCRIPTION_PACKAGE(ROW_ID),
)


alter table [P_PROPERTY] add CONSTRAINT P_PROPERTY_F01 FOREIGN KEY ([ACCNT_ID]) REFERENCES [P_ACCNT](ROW_ID)
alter table [P_UNIT_TYPE] add CONSTRAINT P_UNIT_TYPE_F01 FOREIGN KEY ([PROPERTY_ID]) REFERENCES [P_PROPERTY](ROW_ID)
alter table [P_ACCNT] add CONSTRAINT P_ACCNT_F02 FOREIGN KEY ([ADDR_ID]) REFERENCES [P_ADDR](ROW_ID)
alter table [P_USER] add CONSTRAINT P_USER_P_ACCNT_F01 FOREIGN KEY ([ACCNT_ID]) REFERENCES [P_ACCNT](ROW_ID)
alter table [P_SRV_CATEGORY] add CONSTRAINT P_SRV_CATEGORY_F01 FOREIGN KEY ([ACCNT_ID]) REFERENCES [P_ACCNT](ROW_ID)
alter table [P_SRV_TIC] add CONSTRAINT P_SRV_TIC_F01 FOREIGN KEY ([CASE_OWNER_ID]) REFERENCES [P_USER](ROW_ID)