CREATE TABLE P_ACCNT_OWNER
(
 ROW_ID						    BIGINT IDENTITY(1,1) NOT NULL
,CREATED						DATETIME
,CREATED_BY						BIGINT
,LAST_UPDATED					DATETIME
,LAST_UPDATED_BY				BIGINT
,FIRST_NAME					    NVARCHAR(100)
,LAST_NAME					    NVARCHAR(100)
,USERNAME					    NVARCHAR(100)	               
,PASSWORD                       NVARCHAR(30)
,BIRTH_DT					    DATETIME
,SALUTATION						NVARCHAR(30)
,NATIONALITY                    NVARCHAR(30)
,ID_TYPE						NVARCHAR(30)
,ID_NUM							NVARCHAR(30)
,EMAIL_ADD						NVARCHAR(30)
,MOBILE_NO						NVARCHAR(30)
,HOUSE_NO						NVARCHAR(30)
,OFFICE_NO						NVARCHAR(30)
,FAX_NO							NVARCHAR(30)
,ACCNT_STATUS					NVARCHAR(30)
,ACTIVE_FLG						CHAR(1)
,ADDR_ID						BIGINT
,CACCNT_ID						BIGINT


CONSTRAINT P_ACCNT_OWNER_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)

CONSTRAINT P_ACCNT_OWNER_F01 FOREIGN KEY (ADDR_ID) REFERENCES P_ADDR(ROW_ID),
CONSTRAINT P_ACCNT_OWNER_F02 FOREIGN KEY (CACCNT_ID) REFERENCES P_CON_ACCNT(ROW_ID),
)


alter table P_UNIT add USER_ID bigint
alter table  P_UNIT add OWNER_ID bigint
alter table P_UNIT add CONSTRAINT P_UNIT_F02 FOREIGN KEY (USER_ID) REFERENCES P_USER(ROW_ID)
alter table P_UNIT add CONSTRAINT P_UNIT_F03 FOREIGN KEY (OWNER_ID) REFERENCES P_USER(ROW_ID)