
CREATE TABLE P_BILLING_COMPILE
(
 ROW_ID						    BIGINT IDENTITY(1,1) NOT NULL
,CREATED						DATETIME
,CREATED_BY						BIGINT
,LAST_UPDATED					DATETIME
,LAST_UPDATED_BY				BIGINT

,PROPERTY_ID					BIGINT
,DESCRIPTION					NVARCHAR(MAX)
,AMOUNT							DECIMAL

CONSTRAINT P_BILLING_COMPILE_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)

CONSTRAINT P_BILLING_COMPILE_F01 FOREIGN KEY (PROPERTY_ID) REFERENCES P_PROPERTY(ROW_ID),
)