CREATE TABLE P_UNIT
(
 ROW_ID						    BIGINT IDENTITY(1,1) NOT NULL
,CREATED						DATETIME
,CREATED_BY						BIGINT
,LAST_UPDATED					DATETIME
,LAST_UPDATED_BY				BIGINT
,BLOCK							VARCHAR(255)
,UNIT_NO						VARCHAR(255)
,FLOOR						    VARCHAR(255)
,PROPERTY_ID                    BIGINT

CONSTRAINT P_UNIT_P01 PRIMARY KEY CLUSTERED 
(
	ROW_ID
)

CONSTRAINT P_UNIT_F01 FOREIGN KEY (PROPERTY_ID) REFERENCES P_PROPERTY(ROW_ID),
)